version: "3.9"

services:
  ssta_service:
    extends:
      file: docker-compose.yaml
      service: ssta_service
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/service:/work_dir/service

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - "5432:5432"

volumes:
  posgtres_data:
    driver: local

networks:
  ssta-net:
    driver: bridge