version: "3.9"

services:
  ssta_service:
    extends:
      file: docker-compose.yaml
      service: ssta_service
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/service:/work_dir/service

  autotests:
    extends:
      file: docker-compose.yaml
      service: autotests
    volumes:
      - ${PWD}/autotests:/work_dir/autotests
      - ${PWD}/service/schemas:/work_dir/service/schemas
      - ${PWD}/service/utils:/work_dir/service/utils

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - "5432:5432"

volumes:
  posgtres_data:
    driver: local

networks:
  ssta-net:
    driver: bridge